name: temp_cache
description: A package which provides functionality to store objects inside a temporary cache inside memory
version: 0.0.4
homepage: https://github.com/DirtyNative/temp_cache

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  lint:

flutter:
